### ISSUE TITLE
ModuleNotFoundError: No module named 'recording_pb2'

### ISSUE THREAD

**Issue by XiaoZong0** [DavidGillsjo/VideoIMUCapture-Android#13]
**Describe the bug**
I have read the Protobuf File and did it as instructed. However, When I run data2statistics.py, it always prompts me ModuleNotFoundError: No module named 'recording_pb2'。

**Expected behavior**
![屏幕截图 2023-03-29 170607](https://user-images.githubusercontent.com/49575083/228484563-19a93897-072f-4707-a990-b6339b921b74.jpg)

**Screenshots**
![捕获](https://user-images.githubusercontent.com/49575083/228484080-8f15f681-3515-401d-bb65-aea824192ebf.PNG)

**Comment by DavidGillsjo** [comment]
Hi,
Are you using running the script inside the docker container?
If not, then you need to compile the recording_pb2 python module from the protobuf file.
See [this closed issue](https://github.com/DavidGillsjo/VideoIMUCapture-Android/issues/1) for more information.

The docker container has the module pre-compiled and added to the python path.

**Comment by XiaoZong0** [comment]
> 

Thank you very much.

I have run the script inside the docker container successfully!

**Comment by DavidGillsjo** [comment]
Great, glad it worked!
