### ISSUE TITLE
Global status : warn

### ISSUE THREAD

**Issue by XiaoZong0** [DavidGillsjo/VideoIMUCapture-Android#14]
I have created bag file successfully. However, when I play the baf file in vins-mono, the global status is warn and the track disappears.
Have you ever encountered this kind of problem?
Looking forward to your reply！
![1](https://user-images.githubusercontent.com/49575083/230817091-b2672efb-2f4a-46f8-97de-ba34df16dd40.jpg)

**Comment by DavidGillsjo** [comment]
Hi,
From my experience with ROS, it seems that you are not publishing the transforms through TF messages.
This is strictly an application issue. The positions that you are publishing are published in some reference frame, `world` in this case. But there is no TF transform published that tells rviz the properties of the reference frame `world`.

**Comment by DavidGillsjo** [comment]
I have not used vins-mono so I do not know what error state might cause these warnings.
Maybe the imu and image topics of the bag file does not align with the names that vins-mono expect.
