### ISSUE TITLE
Video capture using front facing camera

### ISSUE THREAD

**Issue by jaykshirsagar05** [DavidGillsjo/VideoIMUCapture-Android#16]
I am interested in using this application to record videos from the front camera. What needs to be changed to do this?

**Comment by DavidGillsjo** [comment]
Hi,
The quick fix would be to alter the [getRearCameraId](https://github.com/DavidGillsjo/VideoIMUCapture-Android/blob/721f62d9585f7b8663a21d10c6d56cd95f30bdcd/android_app/app/src/main/java/se/lth/math/videoimucapture/CameraUtils.java#L86) function to find the front camera ID instead. 

Though it would be nice to create a new setting for choosing camera direction and make a more generic `getCameraId` function that could be used to implement it.
